#secrets:
#  jetbrains_user_pubkey:
#    file: ${JETBRAINS_USER_PUBKEY}

services:
  lstm_aa_app:
    env_file:
      - .env
    image: lstm_aa_app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
#    secrets:
#      - jetbrains_user_pubkey
    build:
      context: ../
      dockerfile: ./app/Dockerfile
      args:
        - PRIMARY_USER=gen_user
#        - JETBRAINS_USER=${JETBRAINS_USER}
#        - WORK_GROUP=${WORK_GROUP}
        - CONTAINER_DEVSPACE=${CONTAINER_DEVSPACE}
        - CONTAINER_PROJECT_ROOT=${CONTAINER_PROJECT_ROOT}
#      secrets:
#        - jetbrains_user_pubkey

    container_name: lstm_aa_app
    entrypoint:
      [
        "/bin/bash",
        "/usr/local/entrypoints/jupyter_lab/main.sh"
      ]
    volumes:
      - ${LOCAL_PROJECT_ROOT}:${CONTAINER_PROJECT_ROOT}
      - /etc/localtime:/etc/localtime:ro

    ports:
#      - "127.0.0.1:${CONTAINER_SSH_PORT}:22"
      - "127.0.0.1:8888:8888"
      - "127.0.0.1:6006:6006"
    init: true
    stdin_open: true
    tty: true
    depends_on:
      - postgres_mimiciii

  postgres_mimiciii:
    image: postgres_mimiciii
    container_name: postgres_mimiciii
    volumes:
      - postgres_mimiciii_db:/var/lib/postgresql/data
    ports:
      - 5555:5432
    init: true
    stdin_open: true
    tty: true

volumes:
  postgres_mimiciii_db:
    external: true





