[db.paths]
mimiciii_db_dotenv = "query_db/mimiciii_database.env"
db_queries = [
    "query_db/mimiciii_queries/icustay_detail.sql",
    "query_db/mimiciii_queries/pivoted_bg.sql",
    "query_db/mimiciii_queries/pivoted_lab.sql",
    "query_db/mimiciii_queries/pivoted_vital.sql",
]
output_dir = "data/query_db"




[paths_rel_root]
lstm_adversarial_attack_package = "src/lstm_adversarial_attack"
data = "data"
docker = "docker"

[subpackages]
db = "query_db"

[paths_rel_db]




#lstm_adversarial_attack_package = $src"/lstm_adversarial_attack"

[preprocess]
min_age = 18
min_los_hospital = 1
min_los_icu = 1
bg_data_cols = [
    "potassium", "calcium", "ph", "pco2", "lactate"
]
lab_data_cols = [
    "albumin",
    "bun",
    "creatinine",
    "sodium",
    "bicarbonate",
    "platelet",
    "glucose",
    "magnesium"
]
vital_data_cols = [
    "heartrate",
    "sysbp",
    "diasbp",
    "tempc",
    "resprate",
    "spo2"
]
admission_data_json_delimiter = "END_TIME_SERIES_DF_METADATA"
winsorize_low = "5%"
winsorize_high = "95%"
resample_interpolation = "linear"
resample_limit_direction = "both"
min_observation_hours = 1
max_observation_hours = 48
require_exact_num_hours = false
observation_window_start = "intime"

[preprocess.prefilter]
icustay_input = "tst_icustay_input.csv"