[preprocess]
min_age = 18
min_los_hospital = 1
min_los_icu = 1
bg_data_cols = [
    "potassium", "calcium", "ph", "pco2", "lactate"
]
lab_data_cols = [
    "albumin",
    "bun",
    "creatinine",
    "sodium",
    "bicarbonate",
    "platelet",
    "glucose",
    "magnesium"
]
vital_data_cols = [
    "heartrate",
    "sysbp",
    "diasbp",
    "tempc",
    "resprate",
    "spo2"
]
admission_data_json_delimiter = "END_TIME_SERIES_DF_METADATA"
winsorize_low = "5%"
winsorize_high = "95%"
resample_interpolation_method = "linear"
resample_limit_direction = "both"
min_observation_hours = 1
max_observation_hours = 48
require_exact_num_hours = false
observation_window_start = "intime"



[preprocess.output_dir_names]
prefilter = "1_prefilter"
measurement_merger = "2_merged_stay_measurements"
admission_list_builder = "3_full_admission_list"
feature_builder = "4_feature_builder"
feature_finalizer = "5_feature_finalizer"

[model]
trainer_eval_general_logging_metrics = [
    "accuracy",
    "auc",
    "f1",
    "precision",
    "recall",
    "validation_loss",
]
trainer_eval_tensorboard_metrics = [
#    "accuracy",
    "auc",
    "f1",
    "precision",
    "recall",
    "validation_loss",
]

[model.trainer]
random_seed = 12345678

[model.tuner_driver]
num_trials = 30
num_folds = 3
num_cv_epochs = 2
epochs_per_fold = 2
kfold_random_seed = 1234
cv_mean_tensorboard_metrics = [
    "accuracy",
    "auc",
    "f1",
    "precision",
    "recall",
    "validation_loss"]
performance_metric = "validation_loss"
optimization_direction_label = "minimize"
tuning_output_dir = "data/model/tuning"
pruner_name = "MedianPruner"
sampler_name = "TPESampler"
db_env_var_name = "MODEL_TUNING_DB_NAME"
fold_class_name = "StratifiedKFold"
collate_fn_name = "x19m_collate_fn"

[model.tuner_driver.tuning_ranges]
log_lstm_hidden_size = [5, 7]
lstm_act_options = ["ReLU", "Tanh"]
dropout = [0.0, 0.5]
log_fc_hidden_size = [4, 8]
fc_act_options = ["ReLU", "Tanh"]
optimizer_options = ["Adam", "RMSprop", "SGD"]
learning_rate = [0.00001, 0.1]
log_batch_size = [5, 8]

[model.tuner_driver.pruner_kwargs]
n_startup_trials = 5
n_warmup_steps = 3

[model.tuner_driver.sampler_kwargs]

[model.cv_driver_settings]
kfold_random_seed = 86420
epochs_per_fold = 20
num_folds = 5
eval_interval = 10
single_fold_eval_fraction = 0.2
fold_class_name = "StratifiedKFold"
collate_fn_name = "x19m_collate_fn"

[model.attr_display_labels]
accuracy = "accuracy"
auc = "AUC"
f1 = "F1"
precision = "precison"
recall = "recall"
validation_loss = "_validation_loss"

[attack.tuning]
kappa = [0.0, 2.0]
lambda_1 = [1e-7, 1.0]
optimizer_options = ["Adam", "RMSprop", "SGD"]
learning_rate = [1e-5, 1.0]
log_batch_size = [5, 7]

[attack.tuner_driver_settings]
db_env_var_name = "ATTACK_TUNING_DB_NAME"
num_trials = 75
epochs_per_batch = 1000
max_num_samples = 520
sample_selection_seed = 2023
pruner_name = "MedianPruner"
sampler_name = "TPESampler"
objective_name = "sparse_small_max"
max_perts = 2    # used when objective_name = "max_num_nonzero_perts"
attack_misclassified_samples = false

[attack.tuner_driver_settings.objective_extra_kwargs]

[attack.tuner_driver_settings.pruner_kwargs]

[attack.tuner_driver_settings.sampler_kwargs]

[attack.analysis]
default_seq_length = 48


[paths]
root_pkg = "src/lstm_adversarial_attack"
output_data = "data"
docker = "docker"

[paths.sub_packages]
db = "root_pkg::query_db"
preprocess = "root_pkg::preprocess"

[paths.db]
mimiciii_dotenv = "sub_packages.db::mimiciii_database.env"
queries_dir = "sub_packages.db::mimiciii_queries"
query_files = [
    "db.queries_dir::icustay_detail.sql",
    "db.queries_dir::pivoted_bg.sql",
    "db.queries_dir::pivoted_lab.sql",
    "db.queries_dir::pivoted_vital.sql"
]
output_root = "output_data::query_db"


[paths.preprocess]
output_root = "output_data::preprocess"

[paths.preprocess.prefilter]
output_dir = "preprocess.output_root::1_prefilter"
[paths.preprocess.prefilter.resources]
icustay = "db.output_root::icustay_detail.csv"
bg = "db.output_root::pivoted_bg.csv"
lab = "db.output_root::pivoted_lab.csv"
vital = "db.output_root::pivoted_vital.csv"

[preprocess.prefilter.resources.icustay]
db = "icustay_detail.csv"
[preprocess.prefilter.resources.bg]
db = "pivoted_bg.csv"
[preprocess.prefilter.resources.lab]
db = "pivoted_lab.csv"
[preprocess.prefilter.resources.vital]
db = "pivoted_vital.csv"

[paths.preprocess.measurement_merger]
output_dir = "preprocess.output_root::2_merged_stay_measurements"

[preprocess.measurement_merger.resources.prefiltered_icustay]
preprocess = "1_prefilter/prefiltered_icustay.feather"
[preprocess.measurement_merger.resources.prefiltered_bg]
preprocess = "1_prefilter/prefiltered_bg.feather"
[preprocess.measurement_merger.resources.prefiltered_lab]
preprocess = "1_prefilter/prefiltered_lab.feather"
[preprocess.measurement_merger.resources.prefiltered_vital]
preprocess = "1_prefilter/prefiltered_vital.feather"

[paths.preprocess.admission_list_builder]
output_dir = "preprocess.output_root::3_full_admission_list"

[preprocess.admission_list_builder.resources.icustay_bg_lab_vital]
preprocess = "2_merged_stay_measurements/icustay_bg_lab_vital.feather"

[paths.preprocess.feature_builder]
output_dir = "preprocess.output_root::4_feature_builder"

[preprocess.feature_builder.resources.bg_lab_vital_summary_stats]
preprocess = "2_merged_stay_measurements/bg_lab_vital_summary_stats.feather"
[preprocess.feature_builder.resources.full_admission_list]
preprocess = "3_full_admission_list/full_admission_list.json"

[paths.preprocess.feature_finalizer]
output_dir = "preprocess.output_root::5_feature_finalizer"

[preprocess.feature_finalizer.resources.processed_admission_list]
preprocess = "4_feature_builder/processed_admission_list.json"

[dataset.resources.measurement_data_list]
preprocess = "5_feature_finalizer/measurement_data_list.json"

[dataset.resources.in_hospital_mortality_list]
preprocess = "5_feature_finalizer/in_hospital_mortality_list.json"

[dataset.resources.measurement_col_names]
preprocess = "5_feature_finalizer/measurement_col_names.json"

[paths.model.tuner_driver]
output_dir = "output_data::model/tuning"

[paths.model.cv_driver]
output_dir = "output_data::model/cross_validation"

[paths.attack.tune]
output_dir = "output_data::attack/tuning"

[paths.attack.tuner_driver]
output_dir = "output_data::attack/tuning"
