
root_pkg = "src/lstm_adversarial_attack"
output_data = "data"

[sub_packages]
db = "root_pkg::query_db"
preprocess = "root_pkg::preprocess"

[db]
mimiciii_dotenv = "sub_packages.db::mimiciii_database.env"
queries_dir = "sub_packages.db::mimiciii_queries"
query_files = [
    "db.queries_dir::icustay_detail.sql",
    "db.queries_dir::pivoted_bg.sql",
    "db.queries_dir::pivoted_lab.sql",
    "db.queries_dir::pivoted_vital.sql"
]
query_output_dir = "output_data::query_db"


[preprocess]
output_root = "output_data::preprocess/checkpoints"

[preprocess.prefilter]
output_dir = "preprocess.output_root::1_prefilter"
[preprocess.prefilter.resources]
icustay = "db.query_output_dir::icustay_detail.csv"
bg = "db.query_output_dir::pivoted_bg.csv"
lab = "db.query_output_dir::pivoted_lab.csv"
vital = "db.query_output_dir::pivoted_vital.csv"

[preprocess.measurement_merger]
output_dir = "preprocess.output_root::2_merged_stay_measurements"
[preprocess.measurement_merger.resources]
prefiltered_icustay = "preprocess.prefilter.output_dir::prefiltered_icustay.feather"
prefiltered_bg = "preprocess.prefilter.output_dir::prefiltered_bg.feather"
prefiltered_lab = "preprocess.prefilter.output_dir::prefiltered_lab.feather"
prefiltered_vital = "preprocess.prefilter.output_dir::prefiltered_vital.feather"

[preprocess.admission_list_builder]
output_dir = "preprocess.output_root::3_full_admission_list"
[preprocess.admission_list_builder.resources]
icustay_bg_lab_vital = "preprocess.measurement_merger.output_dir::icustay_bg_lab_vital.feather"

[preprocess.feature_builder]
output_dir = "preprocess.output_root::4_feature_builder"
[preprocess.feature_builder.resources]
bg_lab_vital_summary_stats = "preprocess.admission_list_builder.output_dir::bg_lab_vital_summary_stats.feather"
full_admission_list = "preprocess.admission_list_builder.output_dir::full_admission_list.json"

[preprocess.feature_finalizer]
output_dir = "preprocess.output_root::5_feature_finalizer"
[preprocess.feature_finalizer.resrources]
processed_admission_list = "preprocess.feature_builder.output_dir::processed_admission_list.json"


[model.tuner_driver]
output_dir = "output_data::model/tuning"

[model.cv_driver]
output_dir = "output_data::model/cross_validation"




