[preprocess]
min_age = 18
min_los_hospital = 1
min_los_icu = 1
bg_data_cols = [ "potassium", "calcium", "ph", "pco2", "lactate",]
lab_data_cols = [ "albumin", "bun", "creatinine", "sodium", "bicarbonate", "platelet", "glucose", "magnesium",]
vital_data_cols = [ "heartrate", "sysbp", "diasbp", "tempc", "resprate", "spo2",]
winsorize_low = "5%"
winsorize_high = "95%"
resample_interpolation_method = "linear"
resample_limit_direction = "both"
min_observation_hours = 48
observation_window_hours = 48
observation_window_start = "intime"

[model]
trainer_eval_general_logging_metrics = [ "accuracy", "auc", "f1", "precision", "recall", "validation_loss",]
trainer_eval_tensorboard_metrics = [ "auc", "f1", "precision", "recall", "validation_loss",]

[model.trainer]
random_seed = 12345678

[model.tuner_driver]
num_trials = 60
num_folds = 5
num_cv_epochs = 10
epochs_per_fold = 5
kfold_random_seed = 1234
performance_metric = "validation_loss"
optimization_direction_label = "minimize"
tuning_output_dir = "data/model/tuning"
pruner_name = "MedianPruner"
sampler_name = "TPESampler"
db_env_var_name = "MODEL_TUNING_DB_NAME"
fold_class_name = "StratifiedKFold"
collate_fn_name = "x19m_collate_fn"
cv_mean_tensorboard_metrics = [ "accuracy", "auc", "f1", "precision", "recall", "validation_loss",]

[model.cv_driver_settings]
collate_fn_name = "x19m_collate_fn"
epochs_per_fold = 1000
eval_interval = 10
fold_class_name = "StratifiedKFold"
kfold_random_seed = 20240807
num_folds = 5
single_fold_eval_fraction = 0.2

[model.attr_display_labels]
accuracy = "accuracy"
auc = "AUC"
f1 = "F1"
precision = "precison"
recall = "recall"
validation_loss = "_validation_loss"

[attack.tuner_driver_settings]
db_env_var_name = "ATTACK_TUNING_DB_NAME"
num_trials = 75
epochs_per_batch = 1000
max_num_samples = 1028
sample_selection_seed = 2023
pruner_name = "MedianPruner"
sampler_name = "TPESampler"
objective_name = "sparse_small_max"
max_perts = 0
attack_misclassified_samples = false

[attack.driver_settings]
epochs_per_batch = 1000
max_num_samples = 1028
sample_selection_seed = 2023
attack_misclassified_samples = false

[attack.analysis]
default_seq_length = 48

[model.tuner_driver.tuning_ranges]
log_lstm_hidden_size = [ 5, 7,]
lstm_act_options = [ "ReLU", "Tanh",]
dropout = [ 0.0, 0.5,]
log_fc_hidden_size = [ 4, 8,]
fc_act_options = [ "ReLU", "Tanh",]
optimizer_options = [ "Adam", "RMSprop", "SGD",]
learning_rate = [ 1e-5, 0.1,]
log_batch_size = [ 5, 8,]

[model.tuner_driver.pruner_kwargs]
n_startup_trials = 5
n_warmup_steps = 3

[model.tuner_driver.sampler_kwargs]

[attack.tuner_driver_settings.objective_extra_kwargs]

[attack.tuner_driver_settings.pruner_kwargs]

[attack.tuner_driver_settings.sampler_kwargs]

[attack.tuning.ranges]
kappa = [ 0.0, 2.0,]
lambda_1 = [ 1e-7, 1.0,]
learning_rate = [ 1e-5, 1.0,]
log_batch_size = [ 5, 7,]
optimizer_options = [ "Adam", "RMSprop", "SGD",]
